export const CAN_VIEW_USER = 'CAN_VIEW_USER';
export const CAN_UPDATE_USER = 'CAN_UPDATE_USER';
export const CAN_UPDATE_USER_AVATAR = 'CAN_UPDATE_USER_AVATAR';
export const CAN_REMOVE_USER = 'CAN_REMOVE_USER';
export const CAN_SOFT_REMOVE_USER = 'CAN_SOFT_REMOVE_USER';
export const CAN_UPDATE_USER_PASSWORD = 'CAN_UPDATE_USER_PASSWORD';
export const CAN_RECOVER_USER = 'CAN_RECOVER_USER';
export const CAN_INACTIVE_USER = 'CAN_INACTIVE_USER';
