/**
 * User
 */
export const CAN_VIEW_USER = 'CAN_VIEW_USER';
export const CAN_UPDATE_USER = 'CAN_UPDATE_USER';
export const CAN_UPDATE_USER_AVATAR = 'CAN_UPDATE_USER_AVATAR';
export const CAN_REMOVE_USER = 'CAN_REMOVE_USER';
export const CAN_SOFT_REMOVE_USER = 'CAN_SOFT_REMOVE_USER';
export const CAN_UPDATE_USER_PASSWORD = 'CAN_UPDATE_USER_PASSWORD';

/**
 * Access Profile
 */
export const CAN_VIEW_ACCESS_PROFILES = 'CAN_VIEW_ACCESS_PROFILES';
export const CAN_CREATE_ACCESS_PROFILE = 'CAN_CREATE_ACCESS_PROFILE';
export const CAN_UPDATE_ACCESS_PROFILE = 'CAN_UPDATE_ACCESS_PROFILE';
export const CAN_REMOVE_ACCESS_PROFILE = 'CAN_REMOVE_ACCESS_PROFILE';
export const CAN_SOFT_REMOVE_ACCESS_PROFILE = 'CAN_SOFT_REMOVE_ACCESS_PROFILE';
export const CAN_RECOVER_ACCESS_PROFILE = 'CAN_RECOVER_ACCESS_PROFILE';
export const CAN_INACTIVE_ACCESS_PROFILE = 'CAN_INACTIVE_ACCESS_PROFILE';
