name: Publish Production

on:
  push:
    branches:
      - master

env:
  PROD_APP_NAME: ${{secrets.HEROKU_APP_NAME}}-prod

jobs:
  validate:
    name: "Validate"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: "16.x"

      - name: Install dependencies
        run: yarn --frozen-lockfile

      - name: Linting
        run: yarn lint

      - name: Type Check
        run: yarn type-check

      - name: Unit Testing
        run: yarn test:coverage

      - name: Upload Coverage
        uses: codecov/codecov-action@v3
        with:
          token: ${{secrets.CODECOV_TOKEN}} # not required for public repos
          directory: coverage
          fail_ci_if_error: true

      - name: Build
        run: yarn build

  publish:
    name: "Publish"
    runs-on: ubuntu-latest
    needs: validate

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{github.head_ref}}

      - name: Login to Heroku
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{env.PROD_APP_NAME}}
          heroku_email: ${{secrets.HEROKU_EMAIL}}
          justlogin: true

      - name: Add Heroku remote
        run: heroku git:remote --app ${{env.PROD_APP_NAME}}

      - name: Push to Heroku
        run: git add -A && git commit -m "Updated code" && git push heroku ${{github.head_ref}}:master

      - name: Running migrations
        run: "heroku run --app ${{env.PROD_APP_NAME}} yarn prod:typeorm:migrate"
