name: Pull Request Synchronize

on:
  pull_request:
    types: [synchronize]

env:
  STAGED_APP_NAME: ${{secrets.HEROKU_APP_NAME}}-${{github.event.number}}

jobs:
  validate:
    name: "Validate"
    runs-on: ubuntu-latest
    if: 1 == 2

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: "16.x"

      - name: Install dependencies
        run: yarn --frozen-lockfile

      - name: Linting
        run: yarn lint

      - name: Type Check
        run: yarn type-check

      - name: Unit Testing
        run: yarn test:coverage

      - name: Upload Coverage
        uses: codecov/codecov-action@v3
        with:
          token: ${{secrets.CODECOV_TOKEN}} # not required for public repos
          directory: coverage
          fail_ci_if_error: true

      - name: Build
        run: yarn build

  publish:
    name: "Publish"
    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.pull_request.labels.*.name, 'skip:publish') || !contains(github.head_ref, 'renovate/') }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}

      - name: Get Pull Request Name
        run: echo ${{ !contains(github.event.pull_request.labels.*.name, 'skip:publish') || !contains(github.head_ref, 'renovate/') }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

