name: Pull Request Synchronize

on:
  pull_request:
    branches-ignore:
      - master
      - dev
    types: [synchronize]

env:
  STAGED_APP_NAME: ${{secrets.HEROKU_APP_NAME}}-${{github.event.number}}
  DEV_APP_NAME: ${{secrets.HEROKU_APP_NAME}}-dev

jobs:
  validate:
    name: "Validate"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: "16.x"
      - name: Install dependencies
        run: yarn --frozen-lockfile
      - name: Formatting
        run: yarn prettier:format
      - name: Linting
        run: yarn lint:fix
      - name: Type Check
        run: yarn type-check
      - name: Unit Testing
        run: yarn test:coverage
      - name: Build
        run: yarn build

  publish:
    name: "Publish"
    runs-on: ubuntu-latest
    needs: validate

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}

      - name: Login to Heroku
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{env.STAGED_APP_NAME}}
          heroku_email: ${{secrets.HEROKU_EMAIL}}
          justlogin: true

      - name: Add Heroku remote
        run: heroku git:remote --app ${{env.STAGED_APP_NAME}}

      - name: Push to Heroku
        run: git push heroku ${{github.head_ref}}:master

      - name: Running migrations
        run: "heroku run --app ${{env.STAGED_APP_NAME}} yarn prod:typeorm:migrate"

      - name: Mark as Published
        run: |
          gh pr comment ${{ github.event.number }} --body 'Republish Successfully: https://${{env.STAGED_APP_NAME}}.herokuapp.com' | gh pr edit --add-label published
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
