name: release staged

on:
  pull_request:
    paths-ignore:
      - 'docs/**'
      - 'README.md'
      - 'LICENSE'
      - '.editorconfig'
      - '.eslintrc.json'
      - '.prettier.config.js'

jobs:
  publish:
    name: "Publish"
    runs-on: ubuntu-latest
    env:
      HEROKU_APP_NAME: staged-${{ github.head_ref }}-${{ github.event.number }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: ${{ github.event.action == 'closed' && 1 || 0 }}
          ref: ${{ github.event.action != 'closed' && github.head_ref || '' }}
      - name: Login to Heroku
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{env.HEROKU_APP_NAME}}
          heroku_email: ${{secrets.HEROKU_EMAIL}}
          justlogin: true
      - name: Create File With Database Credentials
        run: heroku pg:credentials:url --app typeorm-ddd-basic-start > database_credentials
      - name: Handle File With Database Credentials to a valid format
        uses: actions/github-script@v6
        id: set-result
        with:
          script: |
            const script = require('./src/scripts/get_db_credentials.js')
            await script()
