name: release

on:
  pull_request:
    paths-ignore:
      - 'docs/**'
      - 'README.md'
      - 'LICENSE'
      - '.editorconfig'
      - '.eslintrc.json'
      - '.prettier.config.js'

jobs:
  deploy:
    name: "Deploy"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Login to Heroku
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: typeorm-ddd-basic-start
          heroku_email: ${{secrets.HEROKU_EMAIL}}
          justlogin: true
      - name: Add Heroku remote
        run: heroku git:remote --app typeorm-ddd-basic-start
      - run: git fetch
      - name: Show refs
        run: git show-ref
      - name: Push to Heroku
        run: git push heroku ${{ github.head_ref }}:main --force
      - name: Running migrations
        run: "heroku run --app typeorm-ddd-basic-start yarn prod:typeorm:migrate"
        env:
          HD_HOST: ${{secrets.HOST}}
          HD_PG_PORT: ${{secrets.PG_PORT}}
          HD_USERNAME: ${{secrets.USERNAME}}
          HD_PASSWORD: ${{secrets.PASSWORD}}
          HD_DATABASE: ${{secrets.DATABASE}}
