name: release

on:
  pull_request:
    paths-ignore:
      - 'docs/**'
      - 'README.md'
      - 'LICENSE'
      - '.editorconfig'
      - '.eslintrc.json'
      - '.prettier.config.js'

jobs:
  validate:
    name: "Validate"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: "16.x"
      - name: Install dependencies
        run: yarn --frozen-lockfile
      - name: Formatting
        run: yarn prettier:format
      - name: Linting
        run: yarn lint:fix
      - name: Type Check
        run: yarn type-check
      - name: Unit Testing
        run: yarn test:coverage

  deploy:
    name: "Deploy"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: "16.x"
      - name: Install dependencies
        run: yarn --frozen-lockfile
      - name: Build
        run: yarn build
      - name: Deploy
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "typeorm-ddd-basic-start" #Must be unique in Heroku
          heroku_email: "vitorsoares96@hotmail.com"
          buildpack: https://github.com/heroku/heroku-buildpack-nodejs
          procfile: "web: yarn prod:server"
          dontautocreate: true
          branch: "dev"
          remote_branch: "dev"
      - name: Running migrations
        run: "heroku run --app typeorm-ddd-basic-start yarn prod:typeorm:migrate"
        env:
          HD_HOST: ${{secrets.HOST}}
          HD_PG_PORT: ${{secrets.PG_PORT}}
          HD_USERNAME: ${{secrets.USERNAME}}
          HD_PASSWORD: ${{secrets.PASSWORD}}
          HD_DATABASE: ${{secrets.DATABASE}}
