name: release

on:
  pull_request:
    paths-ignore:
      - 'docs/**'
      - 'README.md'
      - 'LICENSE'
      - '.editorconfig'
      - '.eslintrc.json'
      - '.prettier.config.js'

jobs:
  deploy:
    name: "Deploy"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{github.head_ref}}
      - name: Deploy
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "typeorm-ddd-basic-start" #Must be unique in Heroku
          heroku_email: "vitorsoares96@hotmail.com"
          buildpack: https://github.com/heroku/heroku-buildpack-nodejs
          procfile: "web: yarn prod:server"
          justlogin: true
      - name: Add Heroku remote
        run: heroku git:remote --app typeorm-ddd-basic-start
      - name: Push to Heroku
        run: git push heroku ${{github.head_ref}}:master
      - name: Running migrations
        run: "heroku run --app typeorm-ddd-basic-start yarn prod:typeorm:migrate"
        env:
          HD_HOST: ${{secrets.HOST}}
          HD_PG_PORT: ${{secrets.PG_PORT}}
          HD_USERNAME: ${{secrets.USERNAME}}
          HD_PASSWORD: ${{secrets.PASSWORD}}
          HD_DATABASE: ${{secrets.DATABASE}}
